INSERT INTO USER_MIDI (ID,CREATE_TIME,MIDI_FLAG) VALUES 
(1,'{ETL_ID}{TABLE_ID}','UOW_FROM}');

INSERT INTO USER_MIDI (ID,CREATE_TIME,MIDI_FLAG) VALUES 
(1,'{ETL_ID}{TABLE_ID}','{UOW_TO');

INSERT INTO USER_MIDI (ID,CREATE_TIME,MIDI_FLAG) VALUES 
(1,'{ETL_ID}{TABLE_ID}','{UOW_TT}');